export const fleetRows = [
  [
    "creta",
    "Hyundai Creta",
    "SUV",
    5,
    "Automatic",
    "Petrol",
    6500,
    "#bdc5bd",
    "A versatile companion for city streets and scenic escapes. Comfortable seating and room for your weekend essentials.",
  ],
  [
    "swift",
    "Suzuki Swift",
    "Hatchback",
    5,
    "Manual",
    "Petrol",
    3500,
    "#bc563e",
    "Light, compact, and easy to park. A practical choice for discovering the city at your own pace.",
  ],
  [
    "scorpio",
    "Mahindra Scorpio",
    "SUV",
    7,
    "Manual",
    "Diesel",
    8500,
    "#384b42",
    "Room for your crew and the journey ahead. A spacious SUV for group trips on suitable paved roads.",
  ],
  [
    "nexon",
    "Tata Nexon EV",
    "Electric",
    5,
    "Automatic",
    "Electric",
    7000,
    "#588c92",
    "A quiet, all-electric drive for planned routes with charging access. A fresh way to explore.",
  ],
  [
    "city",
    "Honda City",
    "Sedan",
    5,
    "Automatic",
    "Petrol",
    5500,
    "#e1ddd0",
    "A comfortable sedan with a generous cabin. Well suited to everyday journeys and relaxed highway travel.",
  ],
  [
    "venue",
    "Hyundai Venue",
    "SUV",
    5,
    "Manual",
    "Petrol",
    5000,
    "#c79b58",
    "Compact proportions with an elevated driving position. A flexible option for your next short getaway.",
  ],
];
